### ISSUE TITLE
Bot didn't recognize "são carlos" in a second time

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#80] opened 2016-06-20 16:40 UTC
Here bot knows _são carlos_

![firsttime](https://cloud.githubusercontent.com/assets/8461400/16202500/4db188cc-36ec-11e6-8c96-cc9075e78f2d.png)

Then, one message after, doesn't.

![wronganstoquestion](https://cloud.githubusercontent.com/assets/8461400/16202459/30747922-36ec-11e6-95ed-1164b7213311.png)

**Comment by fczuardi** [comment] 2016-06-20 17:11
dupe of #56

**Closed by fczuardi** 2016-06-20 17:11 UTC
Labels: duplicate
