### ISSUE TITLE
Can't change context on the fly when user breaks the regular flow

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#99] opened 2016-06-22 12:46 UTC
![changecontext](https://cloud.githubusercontent.com/assets/8461400/16267019/18022d9e-385e-11e6-819d-946d91ddd139.png)

**Comment by fczuardi** [comment] 2016-06-22 15:36
dupe of #52

**Closed** 2016-06-27 18:16 UTC
Labels: 2 - Working <= 5, duplicate
