### ISSUE TITLE
Bot does not reognize some cities (Sao Paulo, Sao Carlos)

### ISSUE THREAD

**Issue by fredmarques** [fczuardi/calamarcopollo#96] opened 2016-06-22 12:30 UTC
_são Paulo_ and _sao Paulo_ is unknow, but São Paulo it matches.

_são Carlos_ seems to be the same problem.

![photo_2016-06-22_09-27-10](https://cloud.githubusercontent.com/assets/8461400/16266573/f455e0f4-385b-11e6-8fd6-687c8eca7ff1.jpg)

![photo_2016-06-22_09-27-16](https://cloud.githubusercontent.com/assets/8461400/16266572/f4542296-385b-11e6-88da-94d9d0659964.jpg)

**Comment by fczuardi** [comment] 2016-06-22 15:47
possible duplicate of #56

**Comment by fczuardi** [comment] 2016-06-22 15:51
In the case of Sao Paulo, the problem was a Sao Paulo entity without metadata on wit, see screenshots below:

![screenshot 2016-06-22 at 12 14 37 - edited](https://cloud.githubusercontent.com/assets/7760/16273420/dbf85958-3877-11e6-8317-e472fd473f98.png)

![screenshot 2016-06-22 at 12 19 02 - edited](https://cloud.githubusercontent.com/assets/7760/16273432/ebecdbb8-3877-11e6-8fc6-1fe6e084b805.png)

This particular entity I've deleted manually already, but I don't know if it is the same issue for sao carlos

**Closed** 2016-06-27 18:17 UTC
Labels: 2 - Working <= 5, duplicate
